// Static seed data used until Supabase is configured.
// Once your DB is live, these are loaded from the products table instead.

import type { Product, Review } from './types'

export const SEED_PRODUCTS: Product[] = [
  { id: '1',  images: [],name: 'Bloom Crop Top',       description: 'Delicate floral stitch, perfect for layering over bralettes or high-waist pants.',          price: 6800,  emoji: '🌸', bg_color: '#f2d9d0', category: 'crochet',     badge: 'Crochet',   is_new: false, is_bestseller: true,  stock: 3,  rating: 4.9, review_count: 24, sizes: ['XS','S','M','L'],        colors: ['#f2d9d0','#c8d8c0','#dcd3e8'], active: true, created_at: '' },
  { id: '2',  images: [],name: 'Sage Cardigan',        description: 'Oversized open-front cardigan in a soothing sage tone. Pairs beautifully with denim.',       price: 11200, emoji: '🌿', bg_color: '#c8d8c0', category: 'crochet',     badge: 'Crochet',   is_new: true,  is_bestseller: false, stock: 8,  rating: 5.0, review_count: 11, sizes: ['S','M','L','XL'],        colors: ['#c8d8c0','#e8ddd0','#f2d9d0'], active: true, created_at: '' },
  { id: '3',  images: [],name: 'Lavender Slip Dress',  description: 'Flowy hand-sewn chiffon with delicate lace trim and adjustable straps.',                    price: 8800,  emoji: '💜', bg_color: '#dcd3e8', category: 'sewn',        badge: 'Hand-Sewn', is_new: true,  is_bestseller: false, stock: 5,  rating: 4.8, review_count: 8,  sizes: ['XS','S','M','L','XL'],  colors: ['#dcd3e8','#f2d9d0','#e8c4bc'], active: true, created_at: '' },
  { id: '4',  images: [],name: 'Sandy Shorts Set',     description: 'Matching hand-sewn top and relaxed shorts — perfect for beach days or summer errands.',     price: 14500, emoji: '🏖️', bg_color: '#e8ddd0', category: 'sets',        badge: 'Set',       is_new: false, is_bestseller: true,  stock: 2,  rating: 4.7, review_count: 19, sizes: ['XS','S','M','L'],        colors: ['#e8ddd0','#f2d9d0','#c8d8c0'], active: true, created_at: '' },
  { id: '5',  images: [],name: 'Rosette Halter',       description: 'Sweet halter top featuring intricate rosette crochet detailing at the bust.',               price: 5400,  emoji: '🌹', bg_color: '#f2d9d0', category: 'crochet',     badge: 'Crochet',   is_new: false, is_bestseller: false, stock: 10, rating: 4.6, review_count: 15, sizes: ['XS','S','M'],            colors: ['#f2d9d0','#e8c4bc','#dcd3e8'], active: true, created_at: '' },
  { id: '6',  images: [],name: 'Petal Bucket Hat',     description: 'Soft pastel yarn crocheted bucket hat, one size fits all.',                                 price: 3800,  emoji: '🎩', bg_color: '#c8d8c0', category: 'accessories', badge: 'Crochet',   is_new: false, is_bestseller: false, stock: 12, rating: 4.9, review_count: 31, sizes: ['One Size'],              colors: ['#c8d8c0','#f2d9d0','#dcd3e8','#e8c4bc'], active: true, created_at: '' },
  { id: '7',  images: [],name: 'Cloud Midi Skirt',     description: 'Hand-sewn cotton voile midi skirt with an elastic waistband — relaxed and dreamy.',        price: 9800,  emoji: '☁️', bg_color: '#dcd3e8', category: 'sewn',        badge: 'Hand-Sewn', is_new: true,  is_bestseller: false, stock: 6,  rating: 4.8, review_count: 7,  sizes: ['XS','S','M','L','XL'],  colors: ['#dcd3e8','#e8ddd0','#f2d9d0'], active: true, created_at: '' },
  { id: '8',  images: [],name: 'Blush Tote Bag',       description: 'Hand-sewn canvas tote with a braided handle and interior pocket.',                         price: 4600,  emoji: '👜', bg_color: '#e8c4bc', category: 'accessories', badge: 'Hand-Sewn', is_new: false, is_bestseller: false, stock: 9,  rating: 4.5, review_count: 22, sizes: ['One Size'],              colors: ['#e8c4bc','#c8d8c0','#dcd3e8'], active: true, created_at: '' },
  { id: '9',  images: [],name: 'Patchwork Co-ord Set', description: 'Hand-sewn patchwork crop top and wide-leg trousers — a true statement set.',               price: 16500, emoji: '🪡', bg_color: '#f2d9d0', category: 'sets',        badge: 'Hand-Sewn', is_new: true,  is_bestseller: false, stock: 3,  rating: 5.0, review_count: 5,  sizes: ['XS','S','M','L'],        colors: ['#f2d9d0','#c8d8c0','#dcd3e8'], active: true, created_at: '' },
  { id: '10', images: [],name: 'Mesh Crochet Vest',    description: 'Open-weave crochet vest with adjustable ties. Layer over everything.',                     price: 7200,  emoji: '🕸️', bg_color: '#c8d8c0', category: 'crochet',     badge: 'Crochet',   is_new: false, is_bestseller: true,  stock: 7,  rating: 4.7, review_count: 18, sizes: ['XS','S','M','L','XL'],  colors: ['#c8d8c0','#e8ddd0','#f2d9d0'], active: true, created_at: '' },
]

export const SEED_REVIEWS: Review[] = [
  { id: '1', product_id: '1',  reviewer_name: 'Sofia M.',  avatar_letter: 'S', rating: 5, body: 'I absolutely love my Bloom Crop Top. The stitching is so intricate and it fits perfectly. I get compliments every time I wear it!',                              product_name: 'Bloom Crop Top',       created_at: 'Jan 2025' },
  { id: '2', product_id: '9',  reviewer_name: 'Priya K.',  avatar_letter: 'P', rating: 5, body: 'The Patchwork Co-ord Set is a dream. Adya is so talented — you can feel the love in every seam. Will definitely be ordering again.',                           product_name: 'Patchwork Co-ord Set', created_at: 'Feb 2025' },
  { id: '3', product_id: null, reviewer_name: 'Lily T.',   avatar_letter: 'L', rating: 5, body: 'Ordered a custom piece and it was exactly what I imagined. Adya was so communicative and the result was beyond beautiful.',                                    product_name: 'Custom Order',         created_at: 'Dec 2024' },
  { id: '4', product_id: '2',  reviewer_name: 'Amara J.',  avatar_letter: 'A', rating: 4, body: 'The Sage Cardigan is incredibly soft and the color is even better in person. Shipping was fast and the packaging was so cute!',                                product_name: 'Sage Cardigan',        created_at: 'Mar 2025' },
  { id: '5', product_id: '6',  reviewer_name: 'Zoe R.',    avatar_letter: 'Z', rating: 5, body: "My Petal Bucket Hat is the most complimented item I own. I've told everyone where to get it. Adya's work is truly one-of-a-kind.",                            product_name: 'Petal Bucket Hat',     created_at: 'Feb 2025' },
  { id: '6', product_id: '7',  reviewer_name: 'Isla B.',   avatar_letter: 'I', rating: 5, body: 'The Cloud Midi Skirt is SO comfortable and beautiful. I wore it all summer. The hand-sewn details are exquisite.',                                             product_name: 'Cloud Midi Skirt',     created_at: 'Jan 2025' },
]
